#
#   Copyright (C) 2021 Reiko Asakura. All Rights Reserved.
#
#   Vita Development Suite Libraries
#

name: Lint

on:
  pull_request:
  push:
  schedule:
    - cron:  '0 10 * * *'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip3 install ruamel.yaml

      - name: Check NIDs duplicates
        run: |
          python3 scripts/nids-check-dupe.py

      - name: Check NIDs sort
        run: |
          python3 scripts/nids-check-sort.py

      - name: Check NIDs split
        run: |
          python3 scripts/nids-check-split.py

      - name: Check NIDs digest
        run: |
          python3 scripts/nids-check-digest.py

      - name: Check header files
        run: |
          python3 scripts/check-header-files.py
