#ifndef _DOLCESDK_PSP2COMMON_KERNEL_CPU_H_
#define _DOLCESDK_PSP2COMMON_KERNEL_CPU_H_

#define SCE_KERNEL_MAX_CPU            4
#define SCE_KERNEL_CPU_MASK_SHIFT     16
#define SCE_KERNEL_CPU_MASK_USER_0    (0x01 << SCE_KERNEL_CPU_MASK_SHIFT)
#define SCE_KERNEL_CPU_MASK_USER_1    (0x02 << SCE_KERNEL_CPU_MASK_SHIFT)
#define SCE_KERNEL_CPU_MASK_USER_2    (0x04 << SCE_KERNEL_CPU_MASK_SHIFT)
#define SCE_KERNEL_CPU_MASK_USER_3    (0x08 << SCE_KERNEL_CPU_MASK_SHIFT)

#define SCE_KERNEL_CPU_MASK_USER_ALL                         \
	(SCE_KERNEL_CPU_MASK_USER_0 | SCE_KERNEL_CPU_MASK_USER_1 \
		| SCE_KERNEL_CPU_MASK_USER_2)

#define SCE_KERNEL_CPU_MASK_USER_QUAD                        \
	(SCE_KERNEL_CPU_MASK_USER_0 | SCE_KERNEL_CPU_MASK_USER_1 \
		| SCE_KERNEL_CPU_MASK_USER_2 | SCE_KERNEL_CPU_MASK_USER_3)

#endif // _DOLCESDK_PSP2COMMON_KERNEL_CPU_H_
