/*
	Vita Development Suite Libraries
*/

#ifndef _DOLCESDK_PSP2COMMON_KERNEL_CPU_H_
#define _DOLCESDK_PSP2COMMON_KERNEL_CPU_H_

#include_next <kernel/cpu.h>

#define SCE_KERNEL_CPU_MASK_USER_3    (0x08 << SCE_KERNEL_CPU_MASK_SHIFT)

#define SCE_KERNEL_CPU_MASK_USER_QUAD                        \
	(SCE_KERNEL_CPU_MASK_USER_0 | SCE_KERNEL_CPU_MASK_USER_1 \
		| SCE_KERNEL_CPU_MASK_USER_2 | SCE_KERNEL_CPU_MASK_USER_3)

#endif // _DOLCESDK_PSP2COMMON_KERNEL_CPU_H_
